spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xyjhweb?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 1515477256zyh.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

# Spring Boot 启动端口
server:
  port: 9191
# --- MyBatis 配置 ---
mybatis:
  configuration:
    # ！！！在这里添加下面这行关键配置！！！
    map-underscore-to-camel-case: true


# 可选日志配置，方便调试 SQL
# --- 日志配置 ---
logging:
  # 1. 设置不同包的日志级别
  level:
    # 根日志级别，所有日志都遵循这个基础级别
    root: INFO
    # 为你自己的项目包设置更详细的 DEBUG 级别，方便开发调试
    org.xyjh.xyjhstartweb: DEBUG
    # 正确的 MyBatis SQL 日志配置
    org.xyjh.xyjhstartweb.mapper: TRACE
    # 2. 配置文件输出
  file:
      # 定义日志文件的路径和名字
    name: logs/xyjh-start.log

    # 3. 定义控制台和文件的输出格式 (可选，但推荐)
  pattern:
      # 控制台输出格式：带颜色
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
      # 文件输出格式：不带颜色，更简洁
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} --- [%t] %-40.40logger{39} : %m%n%wEx"